name: Pull Hysteria2 Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  pull_hysteria2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout self repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add remote repository
      run: |
        git remote add hysteria2 https://github.com/seagullz4/hysteria2.git
        git fetch hysteria2

    - name: Ensure the local repository is up-to-date
      run: |
        git pull origin main

    - name: Merge remote changes with auto conflict resolution
      run: |
        git merge -X theirs hysteria2/main --allow-unrelated-histories || echo "Merge conflict resolved automatically with 'theirs' strategy."

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
