name: Pull Hysteria2 Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发工作流

jobs:
  pull_hysteria2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout self repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"

    - name: Add remote repository
      run: |
        git remote add hysteria2 https://github.com/seagullz4/hysteria2.git
        git fetch hysteria2

    - name: Merge remote changes
      run: |
        git merge hysteria2/main --allow-unrelated-histories

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
